name: Deploy to AWS Staging

on:
  push:
    branches:
      - staging

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test

      - name: Build Docker image
        run: docker build -t pandacare:latest .

      - name: Save Docker image to tar
        run: docker save pandacare:latest > pandacare.tar

      - name: Compress Docker image
        run: gzip -f pandacare.tar

      - name: Deploy to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
          source: 'pandacare.tar.gz'
          target: '/home/${{ secrets.AWS_USERNAME }}'
          timeout: 120s

      - name: Deploy on EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
          timeout: 120s
          script: |
            # Decompress the Docker image
            gunzip -f /home/${{ secrets.AWS_USERNAME }}/pandacare.tar.gz

            # Load Docker image
            sudo docker load < /home/${{ secrets.AWS_USERNAME }}/pandacare.tar

            # Stop existing container if running
            sudo docker stop pandacare-container || true
            sudo docker rm pandacare-container || true

            # Run new container
            sudo docker run -d --name pandacare-container --restart unless-stopped -p 8080:8080 pandacare:latest

            # Clean up
            rm /home/${{ secrets.AWS_USERNAME }}/pandacare.tar
