name: Deploy to DigitalOcean

on:
  push:
    branches:
      - staging-do
  workflow_dispatch: # Allow manual triggering

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test

      - name: Build Docker image
        run: docker build -t pandacare:latest .

      - name: Save Docker image to tar
        run: docker save pandacare:latest > pandacare.tar

      - name: Compress Docker image
        run: gzip -f pandacare.tar

      - name: Deploy to DigitalOcean Droplet
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USERNAME }}
          key: ${{ secrets.DO_SSH_PRIVATE_KEY }}
          source: "pandacare.tar.gz,docker-compose.yml"
          target: '/home/${{ secrets.DO_USERNAME }}/pandacare-be'
          timeout: 120s

      - name: Deploy on DigitalOcean with docker-compose
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USERNAME }}
          key: ${{ secrets.DO_SSH_PRIVATE_KEY }}
          timeout: 120s
          script: |
            # Navigate to the application directory
            cd /home/${{ secrets.DO_USERNAME }}/pandacare-be
            
            # Decompress the Docker image
            gunzip -f pandacare.tar.gz

            # Load Docker image
            docker load < pandacare.tar

            # Start infrastructure containers (Grafana, Prometheus, etc.)
            docker-compose up -d --remove-orphans

            # Stop existing container if running
            docker stop pandacare-container || true
            docker rm pandacare-container || true

            # Run new container with environment variablesAdd commentMore actions
            docker run -d \
              --name pandacare-container \
              --restart unless-stopped \
              --network pandacare-be_monitoring \
              -p 8090:8080 \
              -e DB_URL="${{ secrets.DB_URL }}" \
              -e DB_USERNAME="${{ secrets.DB_USERNAME }}" \
              -e DB_PASSWORD="${{ secrets.DB_PASSWORD }}" \
              -e JWT_SECRET="${{ secrets.JWT_SECRET }}" \
              pandacare:latest

            # Clean up
            rm pandacare.tar
